---
env:
language: python
python:
  - 3.7
install:
  - pip install ansible-lint
  - ansible-lint --version
  - pip install yamllint
  - yamllint --version
  - pip install napalm-ansible
  - napalm-ansible --version
jobs:
  include:
    - name: Perform yamllint and ansible-lint
      script:
        - yamllint *.yml
        - ansible-lint *.yml
