---
language: python
install:
  - pip install ansible-lint
  - ansible-lint --version
  - pip install yamllint
  - yamllint --version
  - pip install napalm-ansible
  - napalm-ansible --version
jobs:
  include:
    - stage: yaml-lint
      name: yamllint data model playbooks-1
      script: *.yml
    - stage: ansible-lint
      name: ansible-lint data model playbooks-2
      script:
        - ansible-lint 5_Logging_Testing_Validation/ansible/*data-model*.yml
