---
language: python
install:
  - pip install ansible-lint
  - ansible-lint --version
  - pip install yamllint
  - yamllint --version
  - pip install napalm-ansible
  - napalm-ansible --version
jobs:
  include:
    - stage: yaml-lint
      name: yamllint all YAML files
      script: yamllint *.yml
    - stage: ansible-lint
      name: ansible-lint playbooks
      script: ansible-lint *.yml
