---
# yamllint extended configuration file
# Documentation
# https://yamllint.readthedocs.io/en/stable/configuration.html#extending-the-default-configuration
extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 80
    level: warning